spring:
  application:
    name: 'puppies-database-fly'
  datasource:
    url: jdbc:mysql://mysqldb:3306/puppies?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 5
      connectionTimeout: 30000
      idleTimeout: 30000
      poolName: AuthSrvPool
      maxLifetime: 2000000
  jpa:
    database: mysql
    showSql: false
    openInView: true
    hibernate:
      ddlAuto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enableLazyLoadNoTrans: true
        jdbc:
          time_zone: UTC