version: '3.8'

services:
  puppies-rest-api:
    build: .
    container_name: puppies-rest-api
    ports:
      - "8080:8080"
    environment:
      DB_USER: puppies
      DB_PASSWORD: puppies123
    command: [ "/app/rest-api.jar" ]
    networks:
      - puppies-net
    depends_on:
      puppies-flyway:
        condition: service_completed_successfully
      mysqldb:
        condition: service_healthy

  puppies-flyway:
    build:
      context: .
      dockerfile: flyway/Dockerfile
    container_name: puppies-flyway
    environment:
      DB_USER: puppies
      DB_PASSWORD: puppies123
      DB_PORT: 3306
    networks:
      - puppies-net
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: puppies
      MYSQL_USER: puppies
      MYSQL_PASSWORD: puppies123
      MYSQL_ROOT_PASSWORD: puppies123Root
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - puppies-net

networks:
  puppies-net: